version: '3'

services: 
    app:
        build: .
        volumes: 
            - ./:/var/www/html
            - ./rotinasCadastro.daemon.service:/etc/systemd/system/rotinasCadastro.daemon.service
    redis:
        image: redis
        ports:
            - 6379:6379

        
